# Generated by Django 4.0 on 2023-12-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='--', max_length=50, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
